language: go

go:
  - "1.6"
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"

env:
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=386
  - GOOS=linux GOARCH=arm
  - GOOS=freebsd GOARCH=amd64
  - GOOS=freebsd GOARCH=386
  - GOOS=darwin GOARCH=amd64
  - GOOS=darwin GOARCH=386
  - GOOS=windows GOARCH=amd64
  - GOOS=windows GOARCH=386

